<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtSearchBox</name>
   <tag></tag>
   <elementGuidId>a574363a-faab-41e3-b3cd-dc39f7df1878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//android.widget.FrameLayout[@content-desc=&quot;Search&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
